# https://www.home-assistant.io/integrations/default_config/
# default_config:
config:
history:
homeassistant_alerts:
logbook:


# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.integration_blueprint: debug
